# Exploratory Factor Analysis 
***
## Eigenvalues
```{r}
# correlation analysis without mvliking
cor<- cor(vars[,-1])

EV = eigen(cor)$values
EV_df = EV %>%
  # convert to df
  as.data.frame()%>%
  # name column 
  dplyr::rename(., "Eigen Value" =".") %>%
  # add a column "Factor"
  dplyr::mutate(Factor = seq(1,length(EV))) %>%
  # order columns
  dplyr::select(Factor, everything()) %>%
  # add a column "Variance"
  dplyr::mutate(`Variance %` = EV/length(EV) *100) %>%
  dplyr::mutate(`Cumulative Variance % ` = cumsum(EV/length(EV))* 100) %>%
  dplyr::mutate(., across(where(is.numeric), round, 1))

rmarkdown::paged_table(EV_df )
```

### Scree Plot
```{r}
psych::scree(cor, pc = TRUE, factors = FALSE)
```

### Cumulative Percentages of Variance 
```{r}
# Shares for the cumulative variance explained
plot(cumsum(EV/length(EV)), 
     type = "o", # type of plot: "o" for points and lines 'overplotted'
     col = "darkblue",
     pch = 16, # plot symbol: 16 = filled circle
     cex = 1, # size of plot symbols
     xlab = "Number of factors", # a title for the x axis
     ylab = "Cumulative variance explained", # a title for the y axis
     lwd = 2) # line width
abline(v = 5, lwd = 2, col = "grey") # draw a vertical line at v = 3
```

### Select Number of Factors using Kaiser Rule 
```{r}
nFactor <- length(which(EV > 1)) 
print(paste0(nFactor, " factors with Eigenvalue > 1" ))
```

## Extract Principal Factors
```{r}
EFA <- psych::fa(
  r = cor,
  # number of factors
  nfactors = nFactor,
  # principal factor
  fm = "pa",
  # maximizes the sum of the variance of the squared loadings
  rotate = "varimax"
)
```

##  Factor Loadings
```{r}
columnOrder <- c("PA1", "PA2", "PA3", "PA4","PA5","Communality","Uniqueness")

EFA_loadings <- data.frame(EFA$loadings[,]
                           ) %>%
  dplyr::mutate(Uniqueness = EFA$uniquenesses,
                Communality = EFA$communality) %>%
  dplyr::mutate(., across(where(is.numeric), round, 2)) %>%
  dplyr::select(columnOrder) %>%
  arrange(., -Communality)

DT::datatable(EFA_loadings)
```

## Factor Scores
```{r}
# extract rotated factor scores 
EFA.scores = factor.scores(vars[,-1], 
                           unclass(EFA$loadings))$scores 


DT_cols  = c("PA1","PA2","PA3","PA4","PA5")
EFA.scores %>%
  as.data.frame()%>%
  mutate(subjnumb = microvan_df$subjnumb)%>%
  head(5) %>%
  DT::datatable(caption = "Top 5 rows")  %>%
  DT::formatRound(columns=DT_cols , digits=2)


```


